services:
  suenmeow-web:
    restart: always
    environment:
      SUENMEOW_ENV: production
    volumes:
      - ./config:/app/config:ro
      - ./prompts:/app/prompts
      - ./personas:/app/personas
      - ./prompts_public:/app/prompts_public
      - ./personas_public:/app/personas_public
      - suenmeow_data:/app/data
      - ./logs:/app/logs

  suenmeow-public-web:
    restart: always
    environment:
      SUENMEOW_ENV: production
    volumes:
      - ./config:/app/config:ro
      - ./prompts:/app/prompts
      - ./personas:/app/personas
      - ./prompts_public:/app/prompts_public
      - ./personas_public:/app/personas_public
      - suenmeow_data:/app/data
      - ./logs:/app/logs

  suenmeow-worker:
    restart: always
    environment:
      SUENMEOW_ENV: production
    volumes:
      - ./config:/app/config:ro
      - ./prompts:/app/prompts
      - ./personas:/app/personas
      - ./prompts_public:/app/prompts_public
      - ./personas_public:/app/personas_public
      - suenmeow_data:/app/data
      - ./logs:/app/logs
