services:
  suenmeow-web:
    restart: always
    environment:
      SUENMEOW_ENV: production
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./logs:/app/logs

  suenmeow-worker:
    restart: always
    environment:
      SUENMEOW_ENV: production
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./logs:/app/logs
